# Generated by Django 6.0.2 on 2026-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_by_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('college_life', 'College Life'), ('sports', 'Sports')], default='technology', help_text='Select a category for this poll.', max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the poll.'),
        ),
    ]
